version: '1'

services:
  pgs-db-loands:
    container_name: pgs-db-loands
    image: postgres:latest
    environment:
      - POSTGRES_USER=usertest
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=loands-db


  api-django:
    container_name: api-django
    build:
      context: .
      dockerfile: ./Dockerfile

    volumes:
      - ./static:/app/static

    ports:
      - "8001:8001"

    depends_on:
      - pgs-db-loands
