version: '1'

services:
  pgs-db-loands:
    container_name: pgs-db-loands
    image: postgres:latest
    environment:
      - POSTGRES_USER=usertest
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=loands-db
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


  api-django:
    container_name: api-django
    build:
      context: .
      dockerfile: ./Dockerfile

    volumes:
      - ./static:/app/static

    ports:
      - "8080:8080"

    depends_on:
      - pgs-db-loands

volumes:
  postgres-data:

networks:
  my-network:
    driver: bridge
